### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by tushar5526** [tushar5526/Autotype#12]
Autotype now works on all three platforms (win, linux and mac). Update that in readme

**Comment by JeevanJoyal** [comment]
is this issue closed? or can i work on it?

**Comment by GAbdulWahab** [comment]
@JeevanJoyal I think I made PR and found another one had made PR before me

**Comment by JeevanJoyal** [comment]
@GAbdulWahab sorry i was unaware of that , Im new to github, have a great day .

**Comment by tushar5526** [comment]
Hey all, thanks for the contributions. I am quite surprised seeing so many contributors, is there any open source program going on ?

How did you found the project ?

PS: I will merge the first valid PR for this issue, and there are other good first issues available here, and on p5py (another project that I am part of you folks could take a look at)

**Comment by tushar5526** [comment]
Closed by #13

**Comment by GAbdulWahab** [comment]
@tushar5526  
I found your issue here  as **good first issue**
https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by JeevanJoyal** [comment]
@tushar5526 
I found your issue in issues tab in github by searching  is:open language:python label:"good first issue"
your issue is on the top at that time :)
