### ISSUE TITLE
Embed a video or GIF in Readme demonstrating the new UI and CLI version on Autotype

### ISSUE THREAD

**Issue by tushar5526** [tushar5526/Autotype#15]
Currently we have a GIF only for CLI version, which is outdated.

**Comment by tushar5526** [comment]
@RyanWalker277 can you update the GIF as well. I think with all the changes old GIF will confuse everyone

**Comment by RyanWalker277** [comment]
Ya sure , I'll make the necessary changes

**Comment by enrich4real** [comment]
please assign me this issue

**Comment by RyanWalker277** [comment]
Hey @enrich4real , this issue is already closed. But you can have a look at other open issues and mark your precious contribution.
