### ISSUE TITLE
Improvement in the GUI of Autotype.

### ISSUE THREAD

**Issue by AnjumanHasan** [tushar5526/Autotype#23]
# Improvement in the GUI of Autotype.

## Overview
Improvement in the GUI of Autotype for Better User Experience.

## Description

The default GUI of [GUI_script.py](https://github.com/tushar5526/Autotype/blob/main/GUI_script.py) is very Minimal the Approach is to Improve the UI of Autotype to Modern UI standards.

## Expected outcomes
Improved GUI of Autotype
## Skills

Python, Tkinter, Some Knowledge of Design.

## Possible mentors

[Kanishk Pachauri](https://github.com/Mr-Sunglasses), [Anjuman Hassan](https://github.com/AnjumanHasan)

## Expected project size

20 hours.

## Difficulty

Medium

**Comment by AnjumanHasan** [comment]
# Example of Proposal.


# Improve the generated PDF in the PDF/LaTeX backend

### About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 2 years. I
have experienced in Python , JavaScript, and Dart[Flutter] and I am currently learning Julia. I organized events on Open-Source in my College and I am the founding member of an Open-Source community [fossc](https://www.saynotocp.org/) where I mentor Students in their Open-Source Journey. For more information about me You can head over to my [website](https://kanishkpachauri.netlify.app/)
<hr>

### Issue - Intermittent CI failures with PDF builds 
Issue - The "PDF/LaTeX backend" stage often fails on CI, causing the docs not to deploy (since they only deploy if that stage passes) Restarting the build usually fixes it though.

## Proposed Solution….
● Fixing any bug on the CI end.
● Debug any issue in the test of the LaTeX backend
● Rewriting guided Tests for it so that it can be fixed throughout the process.
<hr>

###  TimeLine
## May 20 - June 12
Community bonding, understanding Documenter.jl Codebase, re-scoping project implementation/timeline with help from mentors.

## June 13 - June 23
Learning Julia Essentials and other essentials for integration and fixing of issue #1196 and #1467 and #1342 .

## June 24 - July 15
Adding the Proposed Solution for the issue #1196 and #1467

<hr>

### Commitments.
● I’ll try my best to learn everything which is essential for the
project.
● I’ll Create regular Blog posts on the progress of the project
● I’ll try my best to complete the project on time.
● In case of any change in the above timeline, I will inform
the mentors in advance.
<hr>

---

**Comment by Mr-Sunglasses** [comment]
Resolved in #34 thanks 🙏🏻 @RyanWalker277
