### ISSUE TITLE
Publish Autotype to PIP

### ISSUE THREAD

**Issue by AnjumanHasan** [tushar5526/Autotype#24]
# Publish Autotype to PIP

## Overview
Make Autotype to Install Trough [pip](https://pypi.org/project/pip/)
## Description
Package Installer for Python is the de facto and recommended package-management system written in Python and is used to install and manage software packages. It connects to an online repository of public packages, called the Python Package Index. Our Goal is the publish Autotype to pip so that users can install Autotype Via `pip3 install Autotype` and use is as a command line executable file ex - `Autotype --help`.

## Expected outcomes
pip package for Autotype.

## Skills

Python, pip, Unix Executable File.

## Possible mentors

[Kanishk Pachauri](https://github.com/Mr-Sunglasses), [Anjuman Hassan](https://github.com/AnjumanHasan)

## Expected project size

100 hours.

## Difficulty

Hard

**Comment by AnjumanHasan** [comment]
# Example of Proposal.


# Improve the generated PDF in the PDF/LaTeX backend

### About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 2 years. I
have experienced in Python , JavaScript, and Dart[Flutter] and I am currently learning Julia. I organized events on Open-Source in my College and I am the founding member of an Open-Source community [fossc](https://www.saynotocp.org/) where I mentor Students in their Open-Source Journey. For more information about me You can head over to my [website](https://kanishkpachauri.netlify.app/)
<hr>

### Issue - Intermittent CI failures with PDF builds 
Issue - The "PDF/LaTeX backend" stage often fails on CI, causing the docs not to deploy (since they only deploy if that stage passes) Restarting the build usually fixes it though.

## Proposed Solution….
● Fixing any bug on the CI end.
● Debug any issue in the test of the LaTeX backend
● Rewriting guided Tests for it so that it can be fixed throughout the process.
<hr>

###  TimeLine
## May 20 - June 12
Community bonding, understanding Documenter.jl Codebase, re-scoping project implementation/timeline with help from mentors.

## June 13 - June 23
Learning Julia Essentials and other essentials for integration and fixing of issue #1196 and #1467 and #1342 .

## June 24 - July 15
Adding the Proposed Solution for the issue #1196 and #1467

<hr>

### Commitments.
● I’ll try my best to learn everything which is essential for the
project.
● I’ll Create regular Blog posts on the progress of the project
● I’ll try my best to complete the project on time.
● In case of any change in the above timeline, I will inform
the mentors in advance.
<hr>

---

**Comment by manaswii** [comment]
Hello, could you link a guide or an example on how to do this? I'm interested but i've never done anything similar

**Comment by tushar5526** [comment]
> Hello, could you link a guide or an example on how to do this? I'm interested but i've never done anything similar

https://realpython.com/pypi-publish-python-package/

**Comment by RyanWalker277** [comment]
Greetings, @tushar5526  and @Mr-Sunglasses ! This issue interests me, and I want to work on it. I've never published a Python package, but I believe that by working on this problem, I can learn more about how Python packages operate and how the PYPI publishing process truly works. Please provide me the assignment for this problem.I would request you to assign this issue to me.

**Comment by Mr-Sunglasses** [comment]
Thanks, @RyanWalker277, So I was preparing the [roadmap](https://github.com/tushar5526/Autotype/issues/30) before the first release of Autotype. I'm planning to implement all the features mentioned in that roadmap till this month. So we can plan to release the Autotype to pip in the last week of this month. I'll assign you this issue. But You'll have to properly start working on this issue until I implement the features mentioned in the roadmap.

**Comment by Mr-Sunglasses** [comment]
Before this issue, you can look at #17. You can work on this issue in the meantime.

**Comment by RyanWalker277** [comment]
Thanks @Mr-Sunglasses , I have already started to familiarize myself with the process of packaging scripts. I'll be glad to assist you with the release process. You can connect with me if you think I can assist you with any aspect of the release. Until then , I'll be working on creating the pip wheel for autotype and updating the documentation.

**Comment by Mr-Sunglasses** [comment]
We added it to our target #30
