### ISSUE TITLE
Add a branch to an older version of Autotype and mention it in the docs

### ISSUE THREAD

**Issue by tushar5526** [tushar5526/Autotype#27]
A lot of great features are being added in the Autotype, but I am seeing a need for users simply wanting the old script. I think we can checkout a branch to an old commit and mention the branch in the docs. 

@Mr-Sunglasses you would have to do this when you have the time for it.

**Comment by Mr-Sunglasses** [comment]
@tushar5526, Great Suggestion I will do It by today itself...  👍🏻

**Comment by tushar5526** [comment]
Cool just mention it in the docs somewhere as a Note, and close the issue

**Comment by Mr-Sunglasses** [comment]
@tushar5526 Ok sure
