### ISSUE TITLE
The current Ui of the script can be improved

### ISSUE THREAD

**Issue by RyanWalker277** [tushar5526/Autotype#33]
## Description

The current Ui of the script is a bit outdated and can be replaced with a better looking UI.Instead of tinkter , `customtkinter` library can be used in the `GUI_script.py` for creating a smooth and modern UI

### Changes

- Re-wrote the whole `GUI_script.py`.
- Moved the  `code = """
    class Complex:
        def __init__(self, x, y):
            self.x = x
            self.y = y
        """` block inside the `else` block.This will make the code a bit more cleaner and readable.
- Added a new attribute named `Code` in the `Type` function.
 

## How to test

The new UI can be tested by just running the `GUI_script.py` in a virtual environment having all the `requirements` installed.

### Dark Mode

![image](https://user-images.githubusercontent.com/32684077/197539404-f0eae1cc-c74a-4990-98df-479cee82765c.png)

### Light Mode

![image](https://user-images.githubusercontent.com/32684077/197539666-d88ad0da-73fc-42c7-be48-6fc5d0dcd5e1.png)

**Comment by tushar5526** [comment]
@Mr-Sunglasses can you test this locally?

**Comment by RyanWalker277** [comment]
@Mr-Sunglasses I have added a prompt , to be shown after the script has done writing. Tell me if there are any more changes

**Comment by Mr-Sunglasses** [comment]
@RyanWalker277 Sure Testing the Changes...

**Comment by Mr-Sunglasses** [comment]
@RyanWalker277, @tushar5526 Successfully merged #34. That resolves this issue, So closing this Issue as it was resolved.
