### ISSUE TITLE
Migrate to pipenv

### ISSUE THREAD

**Issue by tushar5526** [tushar5526/Autotype#35]
## Description

Managing python requirements file manually is not a good idea, as it leads to problems down the road. Switch to `pipenv` https://realpython.com/pipenv-guide/

**Comment by nkilm** [comment]
@tushar5526 I want to help in this migration process to `pipenv`, please assign this to me.

**Comment by tushar5526** [comment]
Go ahead. cc @Mr-Sunglasses

**Comment by nkilm** [comment]
@tushar5526 Shall I put the required python version for this project as `3.10.9`? 
As of now latest version viz 3.11.x is facing some problmes(some packages are not getting installed properly).

**Comment by Mr-Sunglasses** [comment]
@nkilm I guess  3.9  will be an optimal version?

**Comment by nkilm** [comment]
@Mr-Sunglasses Alright I'll set the python version to `3.9.0`
