### ISSUE TITLE
Migrate to Pyautogui from Pynput

### ISSUE THREAD

**Issue by Mr-Sunglasses** [tushar5526/Autotype#46]
# Migrate to Pyautogui from Pynput

## Description

Pynput itself contains many other problems and packages to be configured, it is better to use Pyautogui rather than pynput
### Changes

<ul>
   <li> Change dependency to pyautogui from pynput </li>
</ul>

**Comment by Mr-Sunglasses** [comment]
what you think @RyanWalker277 , @tushar5526 .

**Comment by RyanWalker277** [comment]
Yeah! PyautoGUI is the preferred way of sending keystrokes to the OS for our use case. Shifting to it would be a great enhancement.

**Comment by tushar5526** [comment]
It looks good, but can we run it as a headless library as well? Have we tested it for platform support? maybe we can start the development effort on a separate branch. What are the problems with pynput exactly?

**Comment by tushar5526** [comment]
One major issue with. Pynput is to add a sleep timer in between newlines for it to type properly. Sometimes, when the text is large to be typed, it gets messed up on line change. Can you check if pynput is working fine with big texts
